# Generated by Django 3.2.6 on 2021-11-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soc_name', models.CharField(max_length=10)),
                ('soc_img', models.ImageField(upload_to='Social_images', verbose_name='Social Picture')),
                ('link', models.URLField()),
            ],
        ),
    ]
