# Generated by Django 3.2.6 on 2021-11-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_social_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_link',
            name='soc_img',
            field=models.FileField(upload_to='Social_images', verbose_name='Social Picture'),
        ),
    ]
