# Generated by Django 3.2.6 on 2021-11-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_social_link_soc_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social_link',
            options={'ordering': ('soc_name',)},
        ),
    ]
