# Generated by Django 3.2.6 on 2021-11-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_img',
            field=models.ImageField(upload_to='service'),
        ),
    ]
