# Generated by Django 3.2.6 on 2021-11-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_service_service_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('service_img', models.ImageField(upload_to='service')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_img',
        ),
    ]
