# Generated by Django 3.2.6 on 2021-11-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_service_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='service_img',
            name='service_img',
            field=models.ImageField(blank=True, upload_to='service'),
        ),
    ]
