# Generated by Django 3.2.6 on 2021-11-23 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_client_client_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('tab_id', models.CharField(max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tab_context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_img', models.ImageField(upload_to='info/')),
                ('tab_img_name', models.CharField(blank=True, max_length=15)),
                ('tab_text', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.info_tab')),
            ],
        ),
    ]
