# Generated by Django 3.2.6 on 2021-11-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_tab_context_tab_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_tab',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tab_context',
            name='tab_img_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
