# Generated by Django 3.2.6 on 2021-11-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211123_1256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tab_context',
            new_name='Info_tab_context',
        ),
        migrations.AlterModelOptions(
            name='info_tab_context',
            options={'ordering': ('-tab_id',)},
        ),
    ]
